### ISSUE TITLE
Nightly builds?

### ISSUE THREAD

**Issue by phazei** [barryvdh/elfinder-builds#1]
Is this supposed to be auto pulling from the elFinder 2.1 branch?

It's about 4 months behind currently so the laravel-elfinder is missing many fixes.

**Comment by barryvdh** [comment]
Whoops, just updated. I updated the builds and the flysystem driver.

Let me know if anything changed that I need to update ;)

**Comment by anzap** [comment]
Hi Barry, i think this repo is again left behind from the elFinder 2.1 branch missing many fixes, especially performance ones.

**Comment by barryvdh** [comment]
Yes, please download from https://github.com/Studio-42/elFinder/tree/2.1 directly.
It now includes the build files in the 2.1 branch (and source files in 2.1-src)
You can just do: `composer require studio-42/elfinder:"2.1@dev"` for nightly (or without `@dev` for stable releases)

**Comment by barryvdh** [comment]
Marked as deprecated: https://packagist.org/packages/barryvdh/elfinder-builds
